// my-project/src/views/Home.vue
<template>
  <div class="home p-6">
    <el-card class="max-w-md mx-auto">
      <template #header>
        <div class="card-header flex justify-between items-center">
          <span class="text-lg font-semibold">Welcome to Vue 3 + Vite + TypeScript</span>
        </div>
      </template>
      
      <div class="text-center space-y-4">
        <p class="text-gray-600">This is the home page with Element Plus and Tailwind CSS.</p>
        
        <div class="space-y-2">
          <p>Counter: {{ counter.count }}</p>
          <p>Double Count: {{ counter.doubleCount }}</p>
          
          <div class="space-x-2">
            <el-button type="primary" @click="counter.increment">
              <el-icon><Plus /></el-icon>
              Increment
            </el-button>
            <el-button @click="counter.decrement">
              <el-icon><Minus /></el-icon>
              Decrement
            </el-button>
          </div>
        </div>
        
        <router-link to="/about">
          <el-button type="success">Go to About</el-button>
        </router-link>
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { Plus, Minus } from '@element-plus/icons-vue'
import { useCounterStore } from '../stores/counter'

const counter = useCounterStore()
</script>

// demo/test-fixed-template-v3/src/components/Home.tsx
import React from 'react'
import { Card, Button, Space } from 'antd'
import { PlusOutlined, MinusOutlined } from '@ant-design/icons'
import { useSelector, useDispatch } from 'react-redux'
import { RootState } from '../store'
import { increment, decrement } from '../store/counterSlice'
import { Link } from 'react-router-dom'

const Home: React.FC = () => {
  const count = useSelector((state: RootState) => state.counter.value)
  const dispatch = useDispatch()

  return (
    <div className="p-6">
      <Card 
        title="React + TypeScript + Webpack" 
        className="max-w-md mx-auto"
        extra={<Link to="/about"><Button type="primary">About</Button></Link>}
      >
        <div className="text-center space-y-4">
          <p className="text-gray-600">
            This is a React app with TypeScript, Ant Design and Tailwind CSS.
          </p>
          
          <div className="space-y-2">
            <p className="text-lg">Counter: {count}</p>
            <p className="text-sm text-gray-500">Double: {count * 2}</p>
            
            <Space>
              <Button 
                type="primary" 
                icon={<PlusOutlined />}
                onClick={() => dispatch(increment())}
              >
                Increment
              </Button>
              <Button 
                icon={<MinusOutlined />}
                onClick={() => dispatch(decrement())}
              >
                Decrement
              </Button>
            </Space>
          </div>
        </div>
      </Card>
    </div>
  )
}

export default Home
