// scaffold-template/react-webpack-typescript/src/components/About.tsx
import React from 'react'
import { Card, Button, Alert } from 'antd'
import { Link } from 'react-router-dom'

const About: React.FC = () => {
  return (
    <div className="p-6">
      <Card 
        title="About React App" 
        className="max-w-md mx-auto"
        extra={<Link to="/"><Button type="primary">Home</Button></Link>}
      >
        <div className="text-center space-y-4">
          <p className="text-gray-600">
            This is a React application with modern tooling.
          </p>
          
          <Alert
            message="Tech Stack"
            description={
              <ul className="text-left space-y-1 mt-2">
                <li>React 18</li>
                <li>TypeScript</li>
                <li>Webpack (via CRA)</li>
                <li>React Router</li>
                <li>Redux Toolkit</li>
                <li>Ant Design</li>
                <li>Tailwind CSS</li>
              </ul>
            }
            type="info"
            showIcon
          />
        </div>
      </Card>
    </div>
  )
}

export default About

// scaffold-mcp-server/scaffold-template/electron-vite-vue3/src/views/About.vue
<template>
  <div class="about p-6">
    <el-card class="max-w-md mx-auto">
      <template #header>
        <div class="card-header">
          <span class="text-lg font-semibold">About Electron App</span>
        </div>
      </template>
      
      <div class="text-center space-y-4">
        <p class="text-gray-600">This is an Electron desktop application.</p>
        
        <el-alert
          title="Tech Stack"
          type="info"
          :closable="false"
          show-icon
        >
          <ul class="text-left space-y-1">
            <li>Electron</li>
            <li>Vue 3 with Composition API</li>
            <li>TypeScript</li>
            <li>Vite</li>
            <li>Vue Router (Hash Mode)</li>
            <li>Pinia</li>
            <li>Element Plus</li>
            <li>Tailwind CSS</li>
          </ul>
        </el-alert>
        
        <router-link to="/">
          <el-button type="primary">Back to Home</el-button>
        </router-link>
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
// About page for Electron app
</script>
